### ISSUE TITLE
Cannot Generate 3D Hydrocarbon-Stapled Peptides as Described in your paper (Section 3.1)

### ISSUE THREAD

**Issue by Allzzw** [dahuilangda/stapep_package#2] opened 2024-11-25 12:13 UTC
Dear Developers,
I have been using the stapep_package and have tried all the provided .ipynb examples in the /stapep_package/stapep/example directory. However, I am unable to replicate the results mentioned in the paper "Journal of Chemical Information and Modeling", specifically in section 3.1. Example One: Generating 3D Structures for Hydrocarbon-Stapled Peptides.
My issue lies in generating 3D structures for the six stapled peptides (S3, S5, S8, R3, R5, R8). When I attempt to generate 3D structures for any of these sequences, the resulting structures are always linear and lack the expected hydrocarbon staple.
I have tried combinations of the sequences for these peptides, but the result remains the same. I suspect there might be some parameters or additional configurations that need to be specified but are not clear from the documentation or examples.
Thank you for your assistance!

**Comment by dahuilangda** [comment] 2024-11-25 13:04
Dear @Allzzw ,  

Thank you for reaching out with your question regarding the stapep_package and its application to generating 3D structures for hydrocarbon-stapled peptides. To help us better understand the issue, could you provide more specific details or upload the generated results (e.g., the .pdb file for the problematic structure)? This would allow us to diagnose the problem more effectively.  

In the meantime, you can try the following code snippet to generate a 3D structure and save it to a file. 

```python
from stapep.structure import Structure

# Example sequence for hydrocarbon-stapled peptide
seq = 'Ac-BATP-R8-RRR-Aib-BLBR-R3-FKRLQ'

# Initialize the Structure generator
st = Structure(verbose=True)

# Generate the de novo 3D structure and save it to a PDB file
st.de_novo_3d_structure(seq, output_pdb='denovo.pdb')
```

Run this code and upload the resulting `denovo.pdb` file so we can inspect the structure. This might help us pinpoint whether the issue is related to the input sequence, parameters, or package functionality.

**Comment by Allzzw** [comment] 2024-11-25 13:13
Thank you for your response and the guidance provided. I have attempted the steps you suggested, but the resulting structure remains a linear peptide.
To assist with diagnosing the issue, I have attached a ZIP file containing the relevant Jupyter Notebook (.ipynb) and the generated denovo.pdb file. Could you please review them and let me know if you identify any issues or if further adjustments are needed?
Thank you for your time and assistance.
[test.zip](https://github.com/user-attachments/files/17903447/test.zip)

**Comment by dahuilangda** [comment] 2024-11-25 13:32
Dear @Allzzw  

After examining the structure file you provided, I can confirm that the generated structure is correct, including the presence of the hydrocarbon staple. However, the default visualization might not clearly highlight the stapled residues.  

To visually emphasize the stapled residues, you can use the following Python code in a Jupyter Notebook. This code displays the structure in `cartoon` mode by default and highlights the stapled residues in `stick` mode:  

```python
import py3Dmol
from stapep.utils import ProtParamsSeq

# Define the stapled residue names
stapled_resnames = ['S3', 'S6', 'S8', 'R3', 'R6', 'R8']

# Process the sequence to locate stapled residues
pps = ProtParamsSeq(seq)
seq_ = pps.seq_to_list
stapled_residues = [seq_.index(s)+1 for s in seq_ if s in stapled_resnames]

# Load the PDB file
p = py3Dmol.view(query='denovo.pdb')

# Set default style as cartoon
p.setStyle({'model': 0}, {'cartoon': {'color': 'gray'}})

# Highlight stapled residues with stick style
for res in stapled_residues:
    p.addStyle({'model': 0, 'resi': res}, {'stick': {'color': 'orange'}})

# Adjust the view
p.zoomTo()

# Display the visualization
p.show()
```

When you run this code, the stapled residues will be highlighted in `stick` mode (default color: orange) while the rest of the structure is displayed in `cartoon` mode.  

This method provides a clear and accurate visual representation of the hydrocarbon staple in your peptide. Please try this and let us know if you have any further questions!  

![1732540669831](https://github.com/user-attachments/assets/01aeec26-7b5d-4599-bb9f-f1e5499615fc)

**Comment by Allzzw** [comment] 2024-11-25 14:23
Thank you so much for your detailed response and the provided code. I truly appreciate your effort.
I must apologize, as I believe the issue was on my side. The code you provided is incredibly helpful and accurately highlights the structure of the stapled peptide. Before this, I was using a different visualization tool, which yielded inconsistent results. Your solution has clarified the structure perfectly.
————————————————————————————————————————
your code
<img width="725" alt="image" src="https://github.com/user-attachments/assets/6e57177e-2823-42b5-9854-fb9f07ed24e7">
ChimeraX
<img width="1485" alt="image" src="https://github.com/user-attachments/assets/80e18f81-083a-4822-99b3-c60e8662db55">
Pymol
<img width="587" alt="image" src="https://github.com/user-attachments/assets/12b84068-e898-4cc3-bade-1353b764bc91">
Mastro
<img width="965" alt="image" src="https://github.com/user-attachments/assets/4042f0b9-fdf8-4614-b5ae-aabb8b2ce38b">

**Comment by dahuilangda** [comment] 2024-11-25 14:31
Glad it worked out! Closing this issue now. If anything else comes up, feel free to open a new one. 🚀

**Closed as completed by dahuilangda** 2024-11-25 14:31 UTC
